# 03 - Interogari Spark SQL

Scop: rulam 12 interogari SQL relevante pe datasetul curatat. Sunt incluse agregari, filtrari si un join simplu.

In [31]:
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import IntegerType, DoubleType

spark = (
    SparkSession.builder
    .appName("FlightsProject")
    .master("spark://master:7077")
    .config("spark.executor.memory", "1g")
    .config("spark.executor.cores", "1")
    .config("spark.cores.max", "2")
    .config("spark.sql.shuffle.partitions", "4")
    .getOrCreate()
)

Spark version: 3.5.8
Master: spark://master:7077

In [32]:
import pandas as pd

pd.set_option("display.max_columns", 20)
pd.set_option("display.max_colwidth", 40)
pd.set_option("display.width", 140)

def show_small(sdf, n=20):
    return sdf.limit(n).toPandas()

## Incarcare dataset curatat

Notebook-ul citeste CSV-ul curatat salvat de `02_eda_cleanup.ipynb`.

In [33]:
HDFS_CLEAN_CSV = "hdfs://master:9000/flights/clean"

df = (
    spark.read
    .option("header", True)
    .option("inferSchema", True)
    .csv(HDFS_CLEAN_CSV)
    .repartition(4)
)

df.cache()
print("Randuri:", df.count())
df.createOrReplaceTempView("flights")

show_small(df.select(
    "id", "year", "month", "day",
    "origin", "dest", "carrier",
    "dep_delay", "arr_delay", "distance", "speed_mph"
), 10)

Randuri: 327346

       id  year  month  day origin dest carrier  dep_delay  arr_delay  distance   speed_mph
0  326847  2013      9   20    JFK  MCO      B6       -4.0      -22.0       944  475.966387
1  299094  2013      8   21    LGA  DFW      AA       -5.0       12.0      1389  445.668449
2  285921  2013      8    7    EWR  SFO      VX       -2.0       -9.0      2565  437.215909
3  176504  2013      4   12    EWR  PWM      EV      167.0      145.0       284  405.714286
4  133436  2013      2   26    JFK  FLL      B6       -3.0       -2.0      1069  413.806452
5  114448  2013      2    4    LGA  MSP      DL       -3.0      -15.0      1020  402.631579
6   51607  2013     10   27    EWR  RSW      UA       -4.0      -27.0      1068  418.823529
7   15155  2013      1   18    JFK  BTV      B6       -5.0      -16.0       266  312.941176
8  123590  2013      2   15    EWR  LAS      UA        0.0       -5.0      2227  448.389262
9   44336  2013     10   19    EWR  IAH      UA        3.0       19.0      1400  390.697674

## Tabela auxiliara pentru join

Construim o tabela mica `carriers` din dataset, cu cod si nume companie. Name exista si in DF original, dar am facut-o ca sa testam GroupBy.

In [34]:
carriers = df.select("carrier", F.col("name").alias("carrier_name")).dropDuplicates()
carriers.createOrReplaceTempView("carriers")
show_small(carriers.orderBy("carrier"), 20)

   carrier                 carrier_name
0       9E            Endeavor Air Inc.
1       AA       American Airlines Inc.
2       AS         Alaska Airlines Inc.
3       B6              JetBlue Airways
4       DL         Delta Air Lines Inc.
5       EV     ExpressJet Airlines Inc.
6       F9       Frontier Airlines Inc.
7       FL  AirTran Airways Corporation
8       HA       Hawaiian Airlines Inc.
9       MQ                    Envoy Air
10      OO        SkyWest Airlines Inc.
11      UA        United Air Lines Inc.
12      US              US Airways Inc.
13      VX               Virgin America
14      WN       Southwest Airlines Co.
15      YV           Mesa Airlines Inc.

## Q1 - Numar total de zboruri

In [35]:
result = spark.sql("""
SELECT COUNT(*) AS total_flights FROM flights
""")
show_small(result, 20)

   total_flights
0         327346

## Q2 - Zboruri pe carrier

In [36]:
result = spark.sql("""
SELECT carrier, name, COUNT(*) AS flights FROM flights GROUP BY carrier, name ORDER BY flights DESC
""")
show_small(result, 20)

   carrier                         name  flights
0       UA        United Air Lines Inc.    57782
1       B6              JetBlue Airways    54049
2       EV     ExpressJet Airlines Inc.    51108
3       DL         Delta Air Lines Inc.    47658
4       AA       American Airlines Inc.    31947
5       MQ                    Envoy Air    25037
6       US              US Airways Inc.    19831
7       9E            Endeavor Air Inc.    17294
8       WN       Southwest Airlines Co.    12044
9       VX               Virgin America     5116
10      FL  AirTran Airways Corporation     3175
11      AS         Alaska Airlines Inc.      709
12      F9       Frontier Airlines Inc.      681
13      YV           Mesa Airlines Inc.      544
14      HA       Hawaiian Airlines Inc.      342
15      OO        SkyWest Airlines Inc.       29

## Q3 - Intarziere medie la plecare si sosire pe carrier

In [37]:
result = spark.sql("""
SELECT carrier, ROUND(AVG(dep_delay),2) AS avg_dep_delay, ROUND(AVG(arr_delay),2) AS avg_arr_delay FROM flights GROUP BY carrier ORDER BY avg_arr_delay DESC
""")
show_small(result, 20)

   carrier  avg_dep_delay  avg_arr_delay
0       F9          20.20          21.92
1       FL          18.61          20.12
2       EV          19.84          15.80
3       YV          18.90          15.56
4       OO          12.59          11.93
5       MQ          10.45          10.77
6       WN          17.66           9.65
7       B6          12.97           9.46
8       9E          16.44           7.38
9       UA          12.02           3.56
10      US           3.74           2.13
11      VX          12.76           1.76
12      DL           9.22           1.64
13      AA           8.57           0.36
14      HA           4.90          -6.92
15      AS           5.83          -9.93

## Q4 - Top 10 rute dupa numar de zboruri

In [38]:
result = spark.sql("""
SELECT origin, dest, route, COUNT(*) AS flights FROM flights GROUP BY origin, dest, route ORDER BY flights DESC LIMIT 10
""")
show_small(result, 20)

  origin dest    route  flights
0    JFK  LAX  JFK-LAX    11159
1    LGA  ATL  LGA-ATL    10041
2    LGA  ORD  LGA-ORD     8507
3    JFK  SFO  JFK-SFO     8109
4    LGA  CLT  LGA-CLT     5961
5    EWR  ORD  EWR-ORD     5828
6    JFK  BOS  JFK-BOS     5773
7    LGA  MIA  LGA-MIA     5702
8    JFK  MCO  JFK-MCO     5429
9    EWR  BOS  EWR-BOS     5247

## Q5 - Rute cu cele mai mari intarzieri medii

In [39]:
result = spark.sql("""
SELECT route, COUNT(*) AS flights, ROUND(AVG(arr_delay),2) AS avg_arr_delay FROM flights GROUP BY route HAVING flights >= 20 ORDER BY avg_arr_delay DESC LIMIT 10
""")
show_small(result, 20)

     route  flights  avg_arr_delay
0  EWR-CAE       94          44.59
1  EWR-TYS      313          41.15
2  EWR-TUL      294          33.66
3  EWR-OKC      315          30.62
4  EWR-RIC     1615          25.82
5  EWR-MKE     1058          24.00
6  EWR-DSM      390          23.55
7  EWR-MSN      345          23.20
8  EWR-PWM      730          23.01
9  JFK-CMH      705          22.92

## Q6 - Zboruri pe luna

In [40]:
result = spark.sql("""
SELECT month, COUNT(*) AS flights, ROUND(AVG(arr_delay),2) AS avg_arr_delay FROM flights GROUP BY month ORDER BY month
""")
show_small(result, 20)

    month  flights  avg_arr_delay
0       1    26398           6.13
1       2    23611           5.61
2       3    27902           5.81
3       4    27564          11.18
4       5    28128           3.52
5       6    27075          16.48
6       7    28293          16.71
7       8    28756           6.04
8       9    27010          -4.02
9      10    28618          -0.17
10     11    26971           0.46
11     12    27020          14.87

## Q7 - Zboruri pe ora programata

In [41]:
result = spark.sql("""
SELECT hour, COUNT(*) AS flights, ROUND(AVG(dep_delay),2) AS avg_dep_delay FROM flights GROUP BY hour ORDER BY hour
""")
show_small(result, 20)

    hour  flights  avg_dep_delay
0      5     1940           0.69
1      6    25447           1.60
2      7    22475           1.91
3      8    26734           4.11
4      9    19931           4.54
5     10    16370           6.45
6     11    15689           7.15
7     12    17744           8.52
8     13    19457          11.32
9     14    21022          13.70
10    15    23082          16.75
11    16    22045          18.63
12    17    23667          21.00
13    18    21072          20.97
14    19    20507          24.65
15    20    16061          24.25
16    21    10503          24.16
17    22     2558          18.73
18    23     1042          14.02

## Q8 - Procent zboruri intarziate la sosire pe carrier

In [42]:
result = spark.sql("""
SELECT
    carrier,
    COUNT(*) AS flights,
    ROUND(100.0 * AVG(is_arr_delayed), 2) AS pct_arrival_delayed
FROM flights
GROUP BY carrier
ORDER BY pct_arrival_delayed DESC
""")
show_small(result, 20)

   carrier  flights  pct_arrival_delayed
0       F9      681                37.30
1       FL     3175                33.54
2       YV      544                31.43
3       EV    51108                31.36
4       MQ    25037                27.07
5       B6    54049                26.11
6       9E    17294                24.92
7       WN    12044                24.86
8       OO       29                24.14
9       UA    57782                21.79
10      AA    31947                18.79
11      DL    47658                18.23
12      VX     5116                18.06
13      US    19831                17.95
14      AS      709                14.39
15      HA      342                12.57

## Q9 - Distanta medie pe destinatie

In [43]:
result = spark.sql("""
SELECT dest, COUNT(*) AS flights, ROUND(AVG(distance),2) AS avg_distance FROM flights GROUP BY dest HAVING flights >= 20 ORDER BY avg_distance DESC LIMIT 15
""")
show_small(result, 20)

   dest  flights  avg_distance
0   HNL      701       4972.76
1   SFO    13173       2577.93
2   OAK      309       2576.00
3   SJC      328       2569.00
4   SMF      282       2521.00
5   LAX    16026       2468.62
6   BUR      370       2465.00
7   LGB      661       2465.00
8   PDX     1342       2445.61
9   SAN     2709       2437.28
10  SNA      812       2434.00
11  SEA     3885       2412.68
12  LAS     5952       2240.98
13  PHX     4606       2141.34
14  SLC     2451       1986.99

## Q10 - Performanta pe aeroport de origine

In [44]:
result = spark.sql("""
SELECT origin, COUNT(*) AS flights, ROUND(AVG(dep_delay),2) AS avg_dep_delay, ROUND(AVG(arr_delay),2) AS avg_arr_delay FROM flights GROUP BY origin ORDER BY flights DESC
""")
show_small(result, 20)

  origin  flights  avg_dep_delay  avg_arr_delay
0    EWR   117127          15.01           9.11
1    JFK   109079          12.02           5.55
2    LGA   101140          10.29           5.78

## Q11 - Join intre tabela flights si tabela carriers

In [45]:
result = spark.sql("""
SELECT f.name, f.carrier, c.carrier_name, COUNT(*) AS flights, ROUND(AVG(f.arr_delay),2) AS avg_arr_delay FROM flights f JOIN carriers c ON f.carrier = c.carrier GROUP BY f.name, f.carrier, c.carrier_name ORDER BY flights DESC
""")
show_small(result, 20)

                           name carrier                 carrier_name  flights  avg_arr_delay
0         United Air Lines Inc.      UA        United Air Lines Inc.    57782           3.56
1               JetBlue Airways      B6              JetBlue Airways    54049           9.46
2      ExpressJet Airlines Inc.      EV     ExpressJet Airlines Inc.    51108          15.80
3          Delta Air Lines Inc.      DL         Delta Air Lines Inc.    47658           1.64
4        American Airlines Inc.      AA       American Airlines Inc.    31947           0.36
5                     Envoy Air      MQ                    Envoy Air    25037          10.77
6               US Airways Inc.      US              US Airways Inc.    19831           2.13
7             Endeavor Air Inc.      9E            Endeavor Air Inc.    17294           7.38
8        Southwest Airlines Co.      WN       Southwest Airlines Co.    12044           9.65
9                Virgin America      VX               Virgin America     5116           1.76
10  AirTran Airways Corporation      FL  AirTran Airways Corporation     3175          20.12
11         Alaska Airlines Inc.      AS         Alaska Airlines Inc.      709          -9.93
12       Frontier Airlines Inc.      F9       Frontier Airlines Inc.      681          21.92
13           Mesa Airlines Inc.      YV           Mesa Airlines Inc.      544          15.56
14       Hawaiian Airlines Inc.      HA       Hawaiian Airlines Inc.      342          -6.92
15        SkyWest Airlines Inc.      OO        SkyWest Airlines Inc.       29          11.93

## Q12 - Categorii de intarziere

In [46]:
result = spark.sql("""
SELECT CASE WHEN arr_delay <= 0 THEN 'early_or_on_time' WHEN arr_delay <= 15 THEN 'small_delay' WHEN arr_delay <= 60 THEN 'medium_delay' ELSE 'large_delay' END AS delay_category, COUNT(*) AS flights FROM flights GROUP BY CASE WHEN arr_delay <= 0 THEN 'early_or_on_time' WHEN arr_delay <= 15 THEN 'small_delay' WHEN arr_delay <= 60 THEN 'medium_delay' ELSE 'large_delay' END ORDER BY flights DESC
""")
show_small(result, 20)

     delay_category  flights
0  early_or_on_time   194342
1       small_delay    55374
2      medium_delay    49841
3       large_delay    27789

In [47]:
spark.stop()